module.exports = {
  sidebar: [
    'overview',
    'install',
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Classes',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'classes',
            },
          ],
        },
        {
          type: 'category',
          label: 'Interfaces',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'interfaces',
            },
          ],
        },
        {
          type: 'category',
          label: 'Enums',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'enums',
            },
          ],
        },
      ],
    },
  ],
};
